kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ds-pipeline-ui
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  to:
    kind: Service
    name: ds-pipeline-ui
  port:
    targetPort: 8443
  tls:
    termination: Reencrypt
