---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  # ServiceAccounts
  - ./serviceaccounts/postgresql.yaml

  # Secrets
  - ./secrets/postgresql-secret.yaml

  # PersistentVolumeClaims
  - ./persistentvolumeclaims/postgresql-pv-claim.yaml

  # Deployments
  - ./deployments/postgresql.yaml

  # Services
  - ./services/postgresql.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/database_secret
        value: postgresql-secret
    target:
      kind: ConfigMap
      name: kfp-tekton-params-config
      version: v1

images:
  - name: postgresql
    newName: quay.io/internaldatahub/postgresql-96-centos7
    newTag: "9.6"
