apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
    application-crd-id: kubeflow-pipelines
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
      application-crd-id: kubeflow-pipelines
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - name: postgresql
          image: postgresql
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: $(database_secret)
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: $(database_secret)
            - name: POSTGRESQL_DATABASE
              value: kfp-tekton
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 800Mi
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-pv-claim
      volumes:
        - name: postgresql-pv-claim
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
