---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
    application-crd-id: data-science-pipelines
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate  # Need this since backing PVC is ReadWriteOnce, which creates resource lock condition in default Rolling strategy
  selector:
    matchLabels:
      app: mariadb
      application-crd-id: data-science-pipelines
  template:
    metadata:
      labels:
        app: mariadb
        application-crd-id: data-science-pipelines
    spec:
      containers:
        - name: mariadb
          image: mysql
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - "-i"
                - "-c"
                - >-
                  MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D
                  $MYSQL_DATABASE -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: $(database_secret)
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $(database_secret)
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: pipelineDb
                  name: $(pipeline_install_configuration)
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
