apiVersion: v1
kind: Service
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: ds-pipeline-visualizationserver
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: ds-pipeline-visualizationserver
    application-crd-id: data-science-pipelines
