apiVersion: v1
kind: Service
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: ds-pipeline
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: grpc
      port: 8887
      protocol: TCP
      targetPort: 8887
  selector:
    app: ds-pipeline
    application-crd-id: data-science-pipelines
