apiVersion: v1
kind: Service
metadata:
  labels:
    app: ds-pipeline-ui
    application-crd-id: data-science-pipelines
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ds-pipelines-ui-proxy-tls
  name: ds-pipeline-ui
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: ds-pipeline-ui
    application-crd-id: data-science-pipelines
