apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: ds-pipelines-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      application-crd-id: data-science-pipelines
