---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CustomResourceDefinitions
  - ./customresourcedefinitions/viewers.yaml

  # Deployments
  - ./deployments/ds-pipeline-viewer-crd.yaml
  - ./deployments/ds-pipeline-visualizationserver.yaml

  # Rolebindings
  - ./rolebindings/ds-pipeline-viewer-crd.yaml

  # Roles
  - ./roles/ds-pipeline-viewer-controller.yaml

  # ServiceAccounts
  - ./serviceaccounts/ds-pipeline-viewer-crd.yaml
  - ./serviceaccounts/ds-pipeline-viewer.yaml
  - ./serviceaccounts/ds-pipeline-visualizationserver.yaml

  # Services
  - ./services/ds-pipeline-visualizationserver.yaml

images:
  - name: viewer-crd-controller
    newName: gcr.io/ml-pipeline/viewer-crd-controller
    newTag: 1.7.0
  - name: visualization-server
    newName: gcr.io/ml-pipeline/visualization-server
    newTag: 1.7.0
