apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ds-pipeline-ui
    application-crd-id: data-science-pipelines
  name: ds-pipeline-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ds-pipeline-ui
subjects:
  - kind: ServiceAccount
    name: ds-pipeline-ui
