apiVersion: v1
data:
  viewer-pod-template.json: |-
    {
        "spec": {
            "serviceAccountName": "ds-pipelines-viewer"
        }
    }
kind: ConfigMap
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: ds-pipeline-ui-configmap
