apiVersion: v1
kind: Service
metadata:
  labels:
    application-crd-id: data-science-pipelines
  name: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
    application-crd-id: data-science-pipelines
