apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ds-pipeline-persistenceagent
    application-crd-id: data-science-pipelines
  name: ds-pipeline-persistenceagent
spec:
  selector:
    matchLabels:
      app: ds-pipeline-persistenceagent
      application-crd-id: data-science-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: ds-pipeline-persistenceagent
        application-crd-id: data-science-pipelines
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: persistenceagent
          imagePullPolicy: IfNotPresent
          name: ds-pipeline-persistenceagent
          command:
            - persistence_agent
            - "--logtostderr=true"
            - "--namespace=${NAMESPACE}"
            - "--ttlSecondsAfterWorkflowFinish=86400"
            - "--numWorker=2"
            - "--mlPipelineAPIServerName=ds-pipeline"
          livenessProbe:
            exec:
              command:
                - pidof
                - persistence_agent
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - pidof
                - persistence_agent
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 120m
              memory: 500Mi
      serviceAccountName: ds-pipeline-persistenceagent
