apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: ds-pipeline-ui
    application-crd-id: data-science-pipelines
  name: ds-pipeline-ui
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - kubeflow.org
    resources:
      - viewers
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
      - conditions
      - tasks
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
